### ISSUE TITLE
Running in to an issue

### ISSUE THREAD

**Issue by SA7BNT** [Hassassistant/AlexaActionAssistant#1]
Hey,

first of all, thanks for the great work. 
I followed the Youtube how to but am running in to an issue at [https://youtu.be/RlnfmW9MU94](url)
If i try to make the Automation as you do in your video, but just after i type the "t" for text in the service data field when it is blank, im  getting this.
Something you can help me out with?
<img width="1114" alt="Bildschirm­foto 2023-07-22 um 13 36 01" src="https://github.com/Hassassistant/AlexaActionAssistant/assets/35367117/0e760d18-b28a-4d26-ab2a-0a7923f19d9d">

Edit:
Also getting an issue on the script
![Bildschirm­foto 2023-07-22 um 13 43 20](https://github.com/Hassassistant/AlexaActionAssistant/assets/35367117/eab892c8-9ad1-4757-b7a2-cfbc5782f636)

**Comment by danielbrunt57** [comment]
You have the syntax wrong.  By trying to type something at the end of the `data:` line you are inferring a str value.
`data` requires an object like this:
```
service: script.activate_alexa_actionable_notification
continue_on_error: true
data:
  text: Did you prepare your coffee?
  event_id: actionable_notification_coffee_prepared
  alexa_device: "{{ states('sensor.last_alexa') }}"
```
